version: '3.8'

services:
  db:
    image: postgres:15
    container_name: timetracker-postgres
    environment:
      POSTGRES_DB: timetracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local